# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0002_auto_20170527_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagessend',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='messagessend',
            old_name='order_id',
            new_name='order',
        ),
    ]
