# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0002_auto_20170416_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='p_finish_time',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='p_p',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='p_payment',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='p_price',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='p_status',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='p_sub_time',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='p_u',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='ftime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order_code',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment',
            field=models.IntegerField(choices=[(0, '待支付'), (1, '支付成功'), (2, '支付失败')], default=0),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reposition.Users'),
            preserve_default=False,
        ),
    ]
