# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0002_auto_20170502_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='order_id',
        ),
        migrations.AddField(
            model_name='process',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reposition.Orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processstep',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
