# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0003_auto_20170502_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='employee_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='re_mark',
            field=models.TextField(null=True),
        ),
    ]
