# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0003_auto_20170527_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='cprice',
            field=models.FloatField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='original_price',
            field=models.FloatField(verbose_name='原价'),
        ),
    ]
