# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0004_auto_20170502_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.Role'),
        ),
        migrations.AlterField(
            model_name='producttimage',
            name='ul_name',
            field=models.CharField(db_column='ul_Name', max_length=255, null=True),
        ),
    ]
