# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0004_auto_20170529_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态'),
        ),
    ]
