# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0005_auto_20170503_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttimage',
            name='ul_sourcename',
            field=models.CharField(db_column='ul_SourceName', max_length=255, null=True),
        ),
    ]
