# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0005_productpackage_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPackage',
            new_name='Package',
        ),
        migrations.AlterModelTable(
            name='package',
            table='package',
        ),
    ]
