# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0006_auto_20170530_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package2product',
            old_name='product_package',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='product2package',
            old_name='product_package',
            new_name='package',
        ),
    ]
