# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0006_auto_20170503_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalMangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Citys')),
            ],
            options={
                'verbose_name': '区域管理',
                'db_table': 'reginal_management',
                'verbose_name_plural': '区域管理',
            },
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='分类名字'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.ProcessName'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reposition.ProductService'),
        ),
    ]
