# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0007_auto_20170504_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionalMangement',
            new_name='RegionalManagement',
        ),
        migrations.AlterModelTable(
            name='regionalmanagement',
            table='regional_management',
        ),
    ]
