# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0007_auto_20170530_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.SmallIntegerField(choices=[(0, '待付款'), (1, '待服务'), (2, '服务中'), (3, '交易关闭'), (4, '服务完成'), (5, '退款中'), (6, '退款完成')], default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '待付款'), (1, '待服务'), (2, '服务中'), (3, '交易关闭'), (4, '服务完成'), (5, '退款中'), (6, '退款完成')], default=0),
        ),
    ]
