# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0008_auto_20170601_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ul_name', models.CharField(max_length=255, null=True)),
                ('ul_sourcename', models.CharField(max_length=255, null=True)),
                ('ul_type', models.CharField(max_length=10, null=True)),
                ('ul_size', models.IntegerField(null=True)),
                ('ul_posttime', models.DateTimeField(auto_now_add=True)),
                ('ul_url', models.CharField(max_length=100, null=True)),
                ('ul_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Employees')),
                ('ul_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.Products')),
            ],
            options={
                'verbose_name_plural': '文章封面图',
                'verbose_name': '文章封面图',
                'db_table': 'articles_cover_image',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.ArticlesCoverImage'),
        ),
    ]
