# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0008_auto_20170504_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='China',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='citys',
            name='p',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='c',
        ),
        migrations.AlterField(
            model_name='regionalmanagement',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.China'),
        ),
        migrations.DeleteModel(
            name='Citys',
        ),
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.DeleteModel(
            name='Provinces',
        ),
    ]
