# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0009_auto_20170602_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescoverimage',
            name='ul_product',
        ),
    ]
