# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0009_auto_20170504_1929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='china',
            table='china',
        ),
    ]
