# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0010_auto_20170504_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttimage',
            name='ul_product',
            field=models.ForeignKey(db_column='ul_Product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_image', to='reposition.Products'),
        ),
    ]
