# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0011_auto_20170611_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='cover_picture',
            new_name='cover_image',
        ),
    ]
