# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0011_auto_20170505_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalmanagement',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='china',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messagesverifycode',
            name='m_user',
            field=models.ForeignKey(db_column='m_User_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.Users'),
        ),
    ]
