# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0012_auto_20170506_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalmanagement',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionalmanagement',
            name='parent_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionalmanagement',
            name='root_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='china',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
