# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0013_auto_20170506_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.ProductService'),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.ProductCategory'),
        ),
    ]
