# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0013_package_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='优惠卷名称')),
                ('price', models.IntegerField(verbose_name='金额')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('activation', models.IntegerField(default=0, verbose_name='激活数量')),
                ('use_number', models.IntegerField(default=0, verbose_name='使用数量')),
                ('status', models.SmallIntegerField(choices=[(0, '冻结'), (1, '正常')], verbose_name='状态')),
                ('type', models.SmallIntegerField(verbose_name='类型')),
                ('price_reduction', models.IntegerField(null=True, verbose_name='减价')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('isExpired', models.SmallIntegerField(choices=[(0, '已过期'), (1, '未过期')], null=True, verbose_name='是否过期')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Employees', verbose_name='创建人')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.AlterModelTable(
            name='package',
            table='packages',
        ),
    ]
