# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0013_package_weight'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package',
            table='packages',
        ),
    ]
