# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0014_auto_20170506_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_seo_title',
        ),
        migrations.AddField(
            model_name='products',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reposition.RegionalManagement'),
            preserve_default=False,
        ),
    ]
