# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0014_auto_20170616_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='优惠卷名称')),
                ('price', models.IntegerField(verbose_name='金额')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('activation', models.IntegerField(verbose_name='激活数量')),
                ('use_number', models.IntegerField(verbose_name='使用数量')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
                ('type', models.SmallIntegerField(verbose_name='类型')),
                ('valid', models.SmallIntegerField(verbose_name='有效期')),
                ('isExpired', models.SmallIntegerField(verbose_name='是否过期')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Employees')),
            ],
        ),
    ]
