# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0015_auto_20170618_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '无门槛'), (1, '满立减')], verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='coupon2user',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Coupon'),
        ),
        migrations.AddField(
            model_name='coupon2user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Users'),
        ),
    ]
