# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0015_auto_20170507_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='city',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='regionalmanagement',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='regionalmanagement',
            name='root_id',
        ),
        migrations.AddField(
            model_name='regionalmanagement',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionalmanagement',
            name='rid',
            field=models.IntegerField(default=0),
        ),
    ]
