# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0016_auto_20170618_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('url', models.URLField(verbose_name='网址')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], verbose_name='状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='UserConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('content', models.CharField(max_length=200, verbose_name='查询内容')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
            ],
        ),
        migrations.AlterModelTable(
            name='coupon2user',
            table='coupon2user',
        ),
    ]
