# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0017_auto_20170507_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='city',
            new_name='area',
        ),
    ]
