# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0017_auto_20170622_2209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='link',
            table='links',
        ),
        migrations.AlterModelTable(
            name='userconsultation',
            table='user_consultation',
        ),
    ]
