# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0018_auto_20170507_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymengalipy',
            name='out_trade_no',
            field=models.CharField(max_length=20, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='paymengalipy',
            name='trade_no',
            field=models.CharField(max_length=30, verbose_name='支付宝单号'),
        ),
    ]
