# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0018_auto_20170622_2251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userconsultation',
            table='users_consultation',
        ),
    ]
