# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0019_auto_20170622_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='know',
            field=models.SmallIntegerField(choices=[(1, '搜索引擎'), (2, '线下活动'), (3, '微信微博'), (4, '朋友土建'), (5, '名片传单'), (6, '主页'), (7, '其他')], null=True, verbose_name='了解'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='称呼'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=40, null=True, verbose_name='密码'),
        ),
    ]
