# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0019_auto_20170507_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymengalipy',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.OrderPayment'),
        ),
    ]
