# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0020_auto_20170507_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_price', models.FloatField(db_column='p_Price')),
                ('p_market_price', models.FloatField(db_column='p_Market_Price', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paymengalipy',
            name='pay',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='reposition.OrderPayment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='p_details',
            field=models.TextField(db_column='p_Details', verbose_name='产品内容'),
        ),
        migrations.AlterField(
            model_name='regionalmanagement',
            name='pid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regionalmanagement',
            name='rid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product2area',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.RegionalManagement'),
        ),
        migrations.AddField(
            model_name='product2area',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Products'),
        ),
    ]
