# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0020_auto_20170622_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon2user',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.Coupon'),
        ),
    ]
