# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0021_auto_20170625_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('business', models.SmallIntegerField(choices=[(0, '注册公司'), (1, '记账报税'), (2, '工商变更')], verbose_name='业务类型')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='跟进时间')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('isknow', models.SmallIntegerField(choices=[(0, '不知道'), (1, '知道')], verbose_name='客户是否知道用户推荐')),
            ],
            options={
                'db_table': 'user_recommend',
            },
        ),
        migrations.RenameField(
            model_name='clientinfo',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='users',
            name='know',
            field=models.SmallIntegerField(choices=[(1, '搜索引擎'), (2, '线下活动'), (3, '微信微博'), (4, '朋友推荐'), (5, '名片传单'), (6, '主页'), (7, '其他')], null=True, verbose_name='了解'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='姓名'),
        ),
    ]
