# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0022_auto_20170508_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalmanagement',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='regionalmanagement',
            name='rid',
        ),
        migrations.AddField(
            model_name='regionalmanagement',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.RegionalManagement'),
        ),
    ]
