# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0022_auto_20170629_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommend',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
