# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0023_auto_20170508_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalmanagement',
            name='rid',
            field=models.SmallIntegerField(null=True),
        ),
    ]
