# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0023_auto_20170629_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommend',
            name='business',
            field=models.CharField(max_length=100, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='userrecommend',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userrecommend',
            name='isknow',
            field=models.SmallIntegerField(choices=[(0, '不知道'), (1, '知道')], default=0, verbose_name='客户是否知道用户推荐'),
        ),
    ]
