# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0024_auto_20170629_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommend',
            name='ispay',
            field=models.SmallIntegerField(choices=[(0, '未注册'), (1, '已注册')], default=1, verbose_name='是否付款'),
        ),
        migrations.AddField(
            model_name='userrecommend',
            name='isreg',
            field=models.SmallIntegerField(choices=[(0, '未注册'), (1, '已注册')], default=0, verbose_name='是否注册'),
        ),
        migrations.AddField(
            model_name='userrecommend',
            name='recommend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reposition.Users'),
            preserve_default=False,
        ),
    ]
