# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0024_regionalmanagement_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalmanagement',
            name='rid',
            field=models.IntegerField(null=True),
        ),
    ]
