# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0026_auto_20170703_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommend',
            name='isknow',
            field=models.SmallIntegerField(choices=[(0, '不知道'), (1, '知道')], default=0, null=True, verbose_name='客户是否知道用户推荐'),
        ),
    ]
