# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0026_auto_20170509_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalmanagement',
            name='parent',
        ),
        migrations.AddField(
            model_name='regionalmanagement',
            name='p_code',
            field=models.IntegerField(null=True),
        ),
    ]
