# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0027_auto_20170703_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommend',
            name='business',
            field=models.CharField(max_length=100, null=True, verbose_name='业务类型'),
        ),
    ]
