# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0027_auto_20170509_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='city',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='regional_city', to='reposition.RegionalManagement'),
            preserve_default=False,
        ),
    ]
