# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0028_products_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Products')),
            ],
        ),
    ]
