# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0028_auto_20170703_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '工商'), (1, '商标'), (2, '财税'), (3, '其他')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='userrecommend',
            name='isknow',
            field=models.SmallIntegerField(choices=[(0, '不知道'), (1, '知道'), (2, '无')], default=0, null=True, verbose_name='客户是否被推荐'),
        ),
        migrations.AlterField(
            model_name='userrecommend',
            name='recommend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.Users', verbose_name='推荐人'),
        ),
    ]
