# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0029_productrecommend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productrecommend',
            table='product_recommend',
        ),
    ]
