# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0030_productspackages_productspackages2p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspackages',
            old_name='description',
            new_name='pp_description',
        ),
        migrations.RenameField(
            model_name='productspackages',
            old_name='name',
            new_name='pp_name',
        ),
        migrations.RenameField(
            model_name='productspackages2p',
            old_name='price',
            new_name='pp_price',
        ),
        migrations.RenameField(
            model_name='productspackages2p',
            old_name='product',
            new_name='pp_product',
        ),
    ]
