# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0031_auto_20170713_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspackages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reposition.Products'),
            preserve_default=False,
        ),
    ]
