# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0033_productspackages_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspackages2p',
            old_name='pp',
            new_name='pp2p',
        ),
        migrations.RenameField(
            model_name='productspackages2p',
            old_name='pp_price',
            new_name='pp2p_price',
        ),
        migrations.RemoveField(
            model_name='productspackages2p',
            name='pp_product',
        ),
        migrations.AddField(
            model_name='productspackages2p',
            name='pp2p_description',
            field=models.TextField(default=1, verbose_name='产品描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspackages2p',
            name='pp2p_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.Products'),
        ),
    ]
