# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0033_auto_20170511_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommend',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='产品名字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrecommend',
            name='price',
            field=models.FloatField(default=1, verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productrecommend',
            name='description',
            field=models.CharField(max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_name',
            field=models.CharField(db_column='p_Name', max_length=64),
        ),
    ]
