# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0034_auto_20170719_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspackages2p',
            name='pp2p_notbuy',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
