# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0035_productspackages2p_pp2p_notbuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspackages2p',
            name='pp2p_price',
            field=models.IntegerField(null=True, verbose_name='价格'),
        ),
    ]
