# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0036_auto_20170726_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(0, '下架'), (1, '上架')], default=1)),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Employees')),
            ],
            options={
                'db_table': 'banner',
                'verbose_name': '广告位置表',
                'verbose_name_plural': '广告位置表',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.RegionalManagement', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='products',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_city', to='reposition.RegionalManagement', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_category',
            field=models.ForeignKey(db_column='p_Category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='reposition.ProductCategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_ctime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_employee',
            field=models.ForeignKey(db_column='p_Employee_id', on_delete=django.db.models.deletion.DO_NOTHING, to='reposition.Employees', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_market_price',
            field=models.FloatField(db_column='p_Market_Price', null=True, verbose_name='原价格'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_name',
            field=models.CharField(db_column='p_Name', max_length=64, verbose_name='产品名字'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.FloatField(db_column='p_Price', verbose_name='价格'),
        ),
    ]
