# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0036_auto_20170512_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexnav',
            name='ishot',
            field=models.SmallIntegerField(choices=[(0, '不热门'), (1, '热门')], default=1, verbose_name='热门'),
            preserve_default=False,
        ),
    ]
