# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0037_auto_20170821_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
