# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0038_banner_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='weight',
        ),
    ]
