# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0039_remove_banner_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspackages2p',
            name='pp2p_price',
        ),
    ]
