# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0040_remove_productspackages2p_pp2p_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComemnts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_created=True)),
                ('star', models.SmallIntegerField(verbose_name='评分')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('evaluation', models.SmallIntegerField(choices=[(0, '好评'), (1, '中评'), (2, '差评')], verbose_name='评价')),
            ],
            options={
                'verbose_name_plural': '产品评论表',
                'verbose_name': '产品评论表',
                'db_table': 'product_comments',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_province', to='reposition.RegionalManagement', verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='p_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.ProcessStep'),
        ),
        migrations.AlterField(
            model_name='paymengalipy',
            name='buyer_email',
            field=models.CharField(max_length=64, null=True, verbose_name='买家邮箱'),
        ),
        migrations.AlterField(
            model_name='paymengalipy',
            name='buyer_id',
            field=models.CharField(max_length=16, null=True, verbose_name='用户标识'),
        ),
        migrations.AddField(
            model_name='productcomemnts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Products', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productcomemnts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposition.Users', verbose_name='用户id'),
        ),
    ]
