# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0041_auto_20171031_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, verbose_name='用户标识')),
                ('is_subscribe', models.CharField(max_length=1, verbose_name='是否关注公众账号')),
                ('trade_type', models.CharField(max_length=16, verbose_name='交易类型')),
                ('bank_type', models.CharField(max_length=32, verbose_name='付款银行')),
                ('fee_type', models.CharField(max_length=16, verbose_name='货币类型')),
                ('total_fee', models.IntegerField(verbose_name='订单金额(单位为分)')),
                ('settlement_total_fee', models.IntegerField(verbose_name='应结订单金额')),
                ('coupon_fee', models.IntegerField(verbose_name='代金券金额')),
                ('cash_fee_type', models.CharField(max_length=16, verbose_name='现金支付货币类型')),
                ('cash_fee', models.IntegerField(verbose_name='现金支付金额')),
                ('transaction_id', models.CharField(max_length=32, verbose_name='微信支付订单号')),
                ('out_trade_no', models.CharField(max_length=32, verbose_name='商户订单号')),
                ('attach', models.CharField(max_length=128, verbose_name='商家数据包')),
                ('time_end', models.CharField(max_length=14, verbose_name='支付完成时间')),
                ('promotion_detail', models.TextField(verbose_name='营销详情')),
            ],
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待支付'), (1, '支付成功'), (2, '支付失败'), (3, '交易关闭'), (4, '线下支付待确认')], default=0, verbose_name='支付状态'),
        ),
    ]
