# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0042_auto_20171217_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwechat',
            name='appid',
            field=models.CharField(default=1, max_length=32, verbose_name='公众账号ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentwechat',
            name='mch_id',
            field=models.CharField(default=1, max_length=32, verbose_name='商户号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentwechat',
            name='result_code',
            field=models.CharField(default=1, max_length=16, verbose_name='业务结果'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentwechat',
            name='return_code',
            field=models.CharField(default=1, max_length=16, verbose_name='返回状态码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentwechat',
            name='return_msg',
            field=models.CharField(max_length=128, null=True, verbose_name='返回信息'),
        ),
        migrations.AlterField(
            model_name='paymentwechat',
            name='attach',
            field=models.CharField(max_length=128, null=True, verbose_name='商家数据包'),
        ),
        migrations.AlterField(
            model_name='paymentwechat',
            name='cash_fee_type',
            field=models.CharField(max_length=16, null=True, verbose_name='现金支付货币类型'),
        ),
        migrations.AlterField(
            model_name='paymentwechat',
            name='coupon_fee',
            field=models.IntegerField(null=True, verbose_name='代金券金额'),
        ),
        migrations.AlterField(
            model_name='paymentwechat',
            name='promotion_detail',
            field=models.TextField(null=True, verbose_name='营销详情'),
        ),
        migrations.AlterField(
            model_name='paymentwechat',
            name='settlement_total_fee',
            field=models.IntegerField(null=True, verbose_name='应结订单金额'),
        ),
    ]
