# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0043_auto_20171217_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwechat',
            name='sign',
            field=models.CharField(default=1, max_length=32, verbose_name='签名'),
            preserve_default=False,
        ),
    ]
