# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0044_paymentwechat_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentwechat',
            options={'verbose_name': '微信付信息表', 'verbose_name_plural': '微信付信息表'},
        ),
        migrations.AlterModelTable(
            name='paymentwechat',
            table='orders_payment_wechat',
        ),
    ]
