# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reposition', '0045_auto_20171217_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon2user',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reposition.RegionalManagement', verbose_name='区域'),
        ),
    ]
